### ISSUE TITLE
Default options are missing

### ISSUE THREAD

**Issue by fsmanuel** [dockyard/ember-in-viewport#19] opened 2015-05-01 13:58 UTC
That one was hard to track down. I was getting
```
method.apply is not a function TypeError: method.apply is not a function
    at Object.Backburner.run (http://localhost:4000/assets/vendor.js:10755:27)
    at http://localhost:4000/assets/vendor.js:10997:28
```

I figured that it was due to not setting `viewportRefreshRate` in the config. The docs suggest that there are defaults and you don't have to set any config. It is true for `viewportUseRAF`, `viewportEntered` and `viewportListeners` but not for the other options: [_setInitialState](https://github.com/dockyard/ember-in-viewport/blob/develop/addon/mixins/in-viewport.js#L44)

I'm unsure where to set the defaults. I guess `_setInitialState` should be refactored to
```js
  _setInitialState: on('init', function() {
    const options = this._buildOptions({
      viewportUseRAF: canUseRAF(),
      viewportEntered: false,
      viewportListeners: defaultListeners
      // all the other options
    });

    setProperties(this, options);
  })
```

If you are content with it I'll send a PR.

**Comment by fsmanuel** [comment] 2015-05-01 14:10
In addition we should concat `viewportListeners` or is it intentional that setting `viewportListeners: []` in the config would remove the `defaultListeners`?

**Comment by poteto** [comment] 2015-05-01 14:38
Thanks for reporting!

1. Default options are being set in [`config/environment`](https://github.com/dockyard/ember-in-viewport/blob/1.2.1/config/environment.js) of the addon. This gets merged into the consuming app's config, so it *should* be set by default. That config is then injected into the container under `config:in-viewport`, which is [used by the mixin](https://github.com/dockyard/ember-in-viewport/blob/develop/addon%2Fmixins%2Fin-viewport.js#L56). So I'm unsure if that is the cause of the error. Could you post a full stacktrace?

2. That's intentional. If you want to register your own listeners, it means you want to track an element within some container `div`, so registering listeners against the window or document would be unnecessary.

**Comment by fsmanuel** [comment] 2015-05-01 22:36
1. Ok, I'll dig into it. It seems that the addon config isn't merged into the consuming app's config. The stacktrace above is the full stacktrace and it is caused by `viewportRefreshRate` beeing `undefined`. In my consuming app `viewportConfig` is partially set. I just set the `viewportTolerance` that's why I think that the configs aren't cleanly merged.

2. Understood.

**Comment by rwjblue** [comment] 2015-05-02 00:28
@poteto - If a given key exists in the app config, it completely replaces the addon specified config.  In other words, we are not doing a deep merge in ember-cli.

If you need a deep merge, my suggestion is to keep the defaults in `addon/config/default.js`, then use `import defaultConfig from 'ember-in-viewport/config/default';`, and do the merge yourself in the initializer.

**Comment by rwjblue** [comment] 2015-05-02 00:30
I think that comment was somewhat confusing (sorry), let me give an example:


```javascript

// addon's config/environment.js
return {
  thing: {
    foo: 'bar',
    baz: 'qux'
  }
};

// app's config/environment.js
return {
  thing: {
    foo: 'qux'
  }
};
```

The resulting config will be:

```javascript
return {
  thing: {
    foo: 'qux'
  }
};
```

**Comment by poteto** [comment] 2015-05-02 00:43
Ah, I hadn't realized! Thanks for pointing that out @rwjblue. Will issue a fix shortly @fsmanuel

**Comment by fsmanuel** [comment] 2015-05-02 08:38
Thanks to both of you.

**Closed** 2015-05-04 01:48 UTC
