### ISSUE TITLE
Elements taller than viewport never trigger hooks

### ISSUE THREAD

**Issue by awaer** [DockYard/ember-in-viewport#37] opened 2015-08-04 20:00 UTC
I'm running into an issue where tall components (taller than the viewport) don't report that they've entered or exited the viewport. Is there any way to trigger enter/exit/scroll hooks —regardless of whether the _entire_ element is visible— other than by increasing `viewportTolerance` to some pixel value?

Using the waypoints library, one may use a percentage offset from top `{ offset: '100%' }` and be notified as items enter the viewport, regardless of element size. Is this possible with `ember-in-viewport`?

**Comment by regsii** [comment] 2015-09-16 10:18
@awaer @poteto
Looks like this addon doesn't handle case when the element is not in viewport from the very beginning (when `_triggerDidAccessViewport` is called for the first time).
You can think of this like value of `viewportEntered` property is changed from `false` to `false` (since the default value of `viewportEntered` property is `false`).
But `_triggerDidAccessViewport` method only handles change of `viewportEntered` property from `true` to `false` and from `false` to `true`.

https://github.com/dockyard/ember-in-viewport/blob/develop/addon/mixins/in-viewport.js#L130

**Comment by laantorchaweb** [comment] 2015-09-29 19:32
same issue here, I didn't know what was happening until I tried to add smaller elements. But, I can confirm that if the element (component) it's taller than the viewport the events aren't fired.

**Comment by patuku-roy** [comment] 2015-10-23 07:13
@poteto any updates about this? or maybe @awaer already had any enlightenment?

**Comment by awaer** [comment] 2015-10-23 12:52
@patuku-roy My team couldn't find a workaround. The nearest alternative addon (`ember-waypoints`) doesn't meet our use case (and seems to be falling behind), so we opted for rolling our own solution that leans on `scrollMonitor`. It's not ideal, but it works for now.

**Comment by patuku-roy** [comment] 2015-10-26 17:49
Same here, I've tried to use `ember-waypoint` but it seems using the same approach, I ended by splitting the `ember-in-viewport` implementation into many smaller part of the DOM, for example: if I have `div` contains image and text, then I put `ember-in-viewport` for image only, because in my case, the image height always shorter than viewport height, this is not ideal solution but at least working on my problem now.

Btw I will take a look `scrollMonitor` for the second option. Thanks anyway @awaer for your share.

**Comment by Alinaki** [comment] 2016-01-17 22:28
This is very annoying problem on narrow viewports :( When the element is wider than viewport.

**Comment by oligriffiths** [comment] 2016-08-20 17:23
@poteto This still appears to be an issue. Elements taller or wider than the viewport do not trigger the enter/exit hooks. I notice that https://github.com/DockYard/ember-in-viewport/pull/62 attempts to fix the problem but hasn't been merged.

**Comment by poteto** [comment] 2016-08-20 18:01
@oligriffiths Could you try this in your package.json and let me know if it fixes your issue?

```json
"ember-in-viewport": "DockYard/ember-in-viewport#fb64e250ce24c6d6fdf4d53e689b88e96ed96f6c"
```

**Comment by oligriffiths** [comment] 2016-08-21 18:12
@poteto That sort of works, however if the element is initially loaded and partially outside of the viewport, then the enter hook isn't triggered. For example, if the element is partially shown but partially below the bottom of the viewport, the enter hook is not triggered.

**Comment by markmhx** [comment] 2016-12-28 20:14
@poteto I've added https://github.com/DockYard/ember-in-viewport/pull/88/commits/0e316483dccbcf22ba58c375800ba104a1031ba3 to my package.json and it fixes this problem for me. I don't appear to be getting the same issue reported by @oligriffiths. It'd be great to see this branch merged into master so the dependency would be cleaner. Thanks!

**Comment by lifeinafolder** [comment] 2017-01-16 21:23
Any updates on this?

**Comment by danidr** [comment] 2017-07-25 11:04
Hello everyone. Is no one going to merge either of those two fixes? This bug really breaks many use cases...
Thank you.

**Closed** 2018-02-02 04:08 UTC
